org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=2g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.workers.max=4
org.gradle.configureondemand=true
org.gradle.caching=true

kotlin.compiler.execution.strategy=in-process
kotlin.code.style=official