package compose.icons.tablericons

import androidx.compose.ui.graphics.vector.ImageVector
import compose.icons.TablerIcons
import compose.icons.tablericons.filled.Accessible
import compose.icons.tablericons.filled.Ad
import compose.icons.tablericons.filled.Adjustments
import compose.icons.tablericons.filled.Affiliate
import compose.icons.tablericons.filled.Alarm
import compose.icons.tablericons.filled.Alien
import compose.icons.tablericons.filled.Analyze
import compose.icons.tablericons.filled.Apple
import compose.icons.tablericons.filled.Apps
import compose.icons.tablericons.filled.Archive
import compose.icons.tablericons.filled.Artboard
import compose.icons.tablericons.filled.Article
import compose.icons.tablericons.filled.Assembly
import compose.icons.tablericons.filled.Asset
import compose.icons.tablericons.filled.Award
import compose.icons.tablericons.filled.Backspace
import compose.icons.tablericons.filled.Badge
import compose.icons.tablericons.filled.Badges
import compose.icons.tablericons.filled.Balloon
import compose.icons.tablericons.filled.Ballpen
import compose.icons.tablericons.filled.Bandage
import compose.icons.tablericons.filled.Barbell
import compose.icons.tablericons.filled.Basket
import compose.icons.tablericons.filled.Bath
import compose.icons.tablericons.filled.Battery
import compose.icons.tablericons.filled.Bed
import compose.icons.tablericons.filled.Beer
import compose.icons.tablericons.filled.Bell
import compose.icons.tablericons.filled.Bike
import compose.icons.tablericons.filled.Binoculars
import compose.icons.tablericons.filled.Biohazard
import compose.icons.tablericons.filled.Blade
import compose.icons.tablericons.filled.Blender
import compose.icons.tablericons.filled.Blob
import compose.icons.tablericons.filled.Bolt
import compose.icons.tablericons.filled.Bomb
import compose.icons.tablericons.filled.Bone
import compose.icons.tablericons.filled.Bong
import compose.icons.tablericons.filled.Book
import compose.icons.tablericons.filled.Bookmark
import compose.icons.tablericons.filled.Bookmarks
import compose.icons.tablericons.filled.Boom
import compose.icons.tablericons.filled.Bottle
import compose.icons.tablericons.filled.Bow
import compose.icons.tablericons.filled.Bowl
import compose.icons.tablericons.filled.Bread
import compose.icons.tablericons.filled.Briefcase
import compose.icons.tablericons.filled.Brightness
import compose.icons.tablericons.filled.Bubble
import compose.icons.tablericons.filled.Bug
import compose.icons.tablericons.filled.Bulb
import compose.icons.tablericons.filled.Bus
import compose.icons.tablericons.filled.Butterfly
import compose.icons.tablericons.filled.Cactus
import compose.icons.tablericons.filled.Calculator
import compose.icons.tablericons.filled.Calendar
import compose.icons.tablericons.filled.Camera
import compose.icons.tablericons.filled.Campfire
import compose.icons.tablericons.filled.Candle
import compose.icons.tablericons.filled.Cannabis
import compose.icons.tablericons.filled.Capsule
import compose.icons.tablericons.filled.Capture
import compose.icons.tablericons.filled.Car
import compose.icons.tablericons.filled.Carambola
import compose.icons.tablericons.filled.Caravan
import compose.icons.tablericons.filled.Cardboards
import compose.icons.tablericons.filled.Cards
import compose.icons.tablericons.filled.Category
import compose.icons.tablericons.filled.Cherry
import compose.icons.tablericons.filled.Chess
import compose.icons.tablericons.filled.Circle
import compose.icons.tablericons.filled.Circles
import compose.icons.tablericons.filled.Clipboard
import compose.icons.tablericons.filled.Clock
import compose.icons.tablericons.filled.Cloud
import compose.icons.tablericons.filled.Clover
import compose.icons.tablericons.filled.Clubs
import compose.icons.tablericons.filled.Coin
import compose.icons.tablericons.filled.Compass
import compose.icons.tablericons.filled.Cone
import compose.icons.tablericons.filled.Confetti
import compose.icons.tablericons.filled.Container
import compose.icons.tablericons.filled.Contrast
import compose.icons.tablericons.filled.Cookie
import compose.icons.tablericons.filled.Copyleft
import compose.icons.tablericons.filled.Copyright
import compose.icons.tablericons.filled.Cross
import compose.icons.tablericons.filled.Crown
import compose.icons.tablericons.filled.Dashboard
import compose.icons.tablericons.filled.Dialpad
import compose.icons.tablericons.filled.Diamond
import compose.icons.tablericons.filled.Diamonds
import compose.icons.tablericons.filled.Dice
import compose.icons.tablericons.filled.Directions
import compose.icons.tablericons.filled.Disc
import compose.icons.tablericons.filled.Discount
import compose.icons.tablericons.filled.Droplet
import compose.icons.tablericons.filled.Droplets
import compose.icons.tablericons.filled.Dumpling
import compose.icons.tablericons.filled.Egg
import compose.icons.tablericons.filled.Elevator
import compose.icons.tablericons.filled.Engine
import compose.icons.tablericons.filled.Escalator
import compose.icons.tablericons.filled.Exchange
import compose.icons.tablericons.filled.Explicit
import compose.icons.tablericons.filled.Exposure
import compose.icons.tablericons.filled.Eye
import compose.icons.tablericons.filled.Eyeglass
import compose.icons.tablericons.filled.Favicon
import compose.icons.tablericons.filled.Feather
import compose.icons.tablericons.filled.Fence
import compose.icons.tablericons.filled.Ferry
import compose.icons.tablericons.filled.File
import compose.icons.tablericons.filled.Files
import compose.icons.tablericons.filled.Filter
import compose.icons.tablericons.filled.Filters
import compose.icons.tablericons.filled.Flag
import compose.icons.tablericons.filled.Flame
import compose.icons.tablericons.filled.Flare
import compose.icons.tablericons.filled.Flask
import compose.icons.tablericons.filled.Flower
import compose.icons.tablericons.filled.Folder
import compose.icons.tablericons.filled.Folders
import compose.icons.tablericons.filled.Forbid
import compose.icons.tablericons.filled.Fountain
import compose.icons.tablericons.filled.Function
import compose.icons.tablericons.filled.Gauge
import compose.icons.tablericons.filled.Ghost
import compose.icons.tablericons.filled.Gift
import compose.icons.tablericons.filled.Glass
import compose.icons.tablericons.filled.Globe
import compose.icons.tablericons.filled.Golf
import compose.icons.tablericons.filled.Gps
import compose.icons.tablericons.filled.Graph
import compose.icons.tablericons.filled.Headphones
import compose.icons.tablericons.filled.Heart
import compose.icons.tablericons.filled.Helicopter
import compose.icons.tablericons.filled.Hexagon
import compose.icons.tablericons.filled.Home
import compose.icons.tablericons.filled.Hourglass
import compose.icons.tablericons.filled.Icons
import compose.icons.tablericons.filled.Ironing
import compose.icons.tablericons.filled.Jetpack
import compose.icons.tablericons.filled.Key
import compose.icons.tablericons.filled.Keyboard
import compose.icons.tablericons.filled.Keyframe
import compose.icons.tablericons.filled.Keyframes
import compose.icons.tablericons.filled.Label
import compose.icons.tablericons.filled.Layout
import compose.icons.tablericons.filled.Lego
import compose.icons.tablericons.filled.Library
import compose.icons.tablericons.filled.Lifebuoy
import compose.icons.tablericons.filled.Location
import compose.icons.tablericons.filled.Lock
import compose.icons.tablericons.filled.Lungs
import compose.icons.tablericons.filled.Macro
import compose.icons.tablericons.filled.Magnet
import compose.icons.tablericons.filled.Mail
import compose.icons.tablericons.filled.Man
import compose.icons.tablericons.filled.Meeple
import compose.icons.tablericons.filled.Melon
import compose.icons.tablericons.filled.Message
import compose.icons.tablericons.filled.Meteor
import compose.icons.tablericons.filled.Mickey
import compose.icons.tablericons.filled.Microphone
import compose.icons.tablericons.filled.Microscope
import compose.icons.tablericons.filled.Microwave
import compose.icons.tablericons.filled.Milk
import compose.icons.tablericons.filled.Moon
import compose.icons.tablericons.filled.Motorbike
import compose.icons.tablericons.filled.Mountain
import compose.icons.tablericons.filled.Mouse
import compose.icons.tablericons.filled.Mug
import compose.icons.tablericons.filled.Mushroom
import compose.icons.tablericons.filled.Navigation
import compose.icons.tablericons.filled.Nurse
import compose.icons.tablericons.filled.Octagon
import compose.icons.tablericons.filled.Oval
import compose.icons.tablericons.filled.Paint
import compose.icons.tablericons.filled.Palette
import compose.icons.tablericons.filled.Paw
import compose.icons.tablericons.filled.Pennant
import compose.icons.tablericons.filled.Pentagon
import compose.icons.tablericons.filled.Phone
import compose.icons.tablericons.filled.Photo
import compose.icons.tablericons.filled.Pig
import compose.icons.tablericons.filled.Pill
import compose.icons.tablericons.filled.Pin
import compose.icons.tablericons.filled.Pinned
import compose.icons.tablericons.filled.Pizza
import compose.icons.tablericons.filled.Point
import compose.icons.tablericons.filled.Pointer
import compose.icons.tablericons.filled.Polaroid
import compose.icons.tablericons.filled.Poo
import compose.icons.tablericons.filled.Presentation
import compose.icons.tablericons.filled.Puzzle
import compose.icons.tablericons.filled.Quote
import compose.icons.tablericons.filled.Radar
import compose.icons.tablericons.filled.Radioactive
import compose.icons.tablericons.filled.Receipt
import compose.icons.tablericons.filled.Rectangle
import compose.icons.tablericons.filled.Registered
import compose.icons.tablericons.filled.Replace
import compose.icons.tablericons.filled.Rollercoaster
import compose.icons.tablericons.filled.Rosette
import compose.icons.tablericons.filled.Salad
import compose.icons.tablericons.filled.Section
import compose.icons.tablericons.filled.Seedling
import compose.icons.tablericons.filled.Settings
import compose.icons.tablericons.filled.Shield
import compose.icons.tablericons.filled.Shirt
import compose.icons.tablericons.filled.Sitemap
import compose.icons.tablericons.filled.Soup
import compose.icons.tablericons.filled.Spade
import compose.icons.tablericons.filled.Speedboat
import compose.icons.tablericons.filled.Spider
import compose.icons.tablericons.filled.Square
import compose.icons.tablericons.filled.Squares
import compose.icons.tablericons.filled.Stack
import compose.icons.tablericons.filled.Star
import compose.icons.tablericons.filled.Stars
import compose.icons.tablericons.filled.Sun
import compose.icons.tablericons.filled.Sunglasses
import compose.icons.tablericons.filled.Sunrise
import compose.icons.tablericons.filled.Sunset
import compose.icons.tablericons.filled.Table
import compose.icons.tablericons.filled.Tag
import compose.icons.tablericons.filled.Tags
import compose.icons.tablericons.filled.Template
import compose.icons.tablericons.filled.Train
import compose.icons.tablericons.filled.Transform
import compose.icons.tablericons.filled.Trash
import compose.icons.tablericons.filled.Triangle
import compose.icons.tablericons.filled.Trolley
import compose.icons.tablericons.filled.Trophy
import compose.icons.tablericons.filled.Truck
import compose.icons.tablericons.filled.Ufo
import compose.icons.tablericons.filled.Umbrella
import compose.icons.tablericons.filled.User
import compose.icons.tablericons.filled.Versions
import compose.icons.tablericons.filled.Video
import compose.icons.tablericons.filled.Windmill
import compose.icons.tablericons.filled.Windsock
import compose.icons.tablericons.filled.Woman
import compose.icons.tablericons.filled.Writing
import compose.icons.tablericons.filled.Zeppelin
import compose.icons.tablericons.filled.Zoom
import compose.icons.tablericons.filled.`Ad-circle`
import compose.icons.tablericons.filled.`Aerial-lift`
import compose.icons.tablericons.filled.`Air-balloon`
import compose.icons.tablericons.filled.`Alarm-minus`
import compose.icons.tablericons.filled.`Alarm-plus`
import compose.icons.tablericons.filled.`Alarm-snooze`
import compose.icons.tablericons.filled.`Alert-circle`
import compose.icons.tablericons.filled.`Alert-hexagon`
import compose.icons.tablericons.filled.`Alert-octagon`
import compose.icons.tablericons.filled.`Alert-square-rounded`
import compose.icons.tablericons.filled.`Alert-square`
import compose.icons.tablericons.filled.`Alert-triangle`
import compose.icons.tablericons.filled.`Align-box-bottom-center`
import compose.icons.tablericons.filled.`Align-box-bottom-left`
import compose.icons.tablericons.filled.`Align-box-bottom-right`
import compose.icons.tablericons.filled.`Align-box-center-middle`
import compose.icons.tablericons.filled.`Align-box-left-bottom`
import compose.icons.tablericons.filled.`Align-box-left-middle`
import compose.icons.tablericons.filled.`Align-box-left-top`
import compose.icons.tablericons.filled.`Align-box-right-bottom`
import compose.icons.tablericons.filled.`Align-box-right-middle`
import compose.icons.tablericons.filled.`Align-box-right-top`
import compose.icons.tablericons.filled.`Align-box-top-center`
import compose.icons.tablericons.filled.`Align-box-top-left`
import compose.icons.tablericons.filled.`Align-box-top-right`
import compose.icons.tablericons.filled.`App-window`
import compose.icons.tablericons.filled.`Arrow-autofit-content`
import compose.icons.tablericons.filled.`Arrow-autofit-down`
import compose.icons.tablericons.filled.`Arrow-autofit-height`
import compose.icons.tablericons.filled.`Arrow-autofit-left`
import compose.icons.tablericons.filled.`Arrow-autofit-right`
import compose.icons.tablericons.filled.`Arrow-autofit-up`
import compose.icons.tablericons.filled.`Arrow-autofit-width`
import compose.icons.tablericons.filled.`Arrow-badge-down`
import compose.icons.tablericons.filled.`Arrow-badge-left`
import compose.icons.tablericons.filled.`Arrow-badge-right`
import compose.icons.tablericons.filled.`Arrow-badge-up`
import compose.icons.tablericons.filled.`Arrow-big-down-line`
import compose.icons.tablericons.filled.`Arrow-big-down-lines`
import compose.icons.tablericons.filled.`Arrow-big-down`
import compose.icons.tablericons.filled.`Arrow-big-left-line`
import compose.icons.tablericons.filled.`Arrow-big-left-lines`
import compose.icons.tablericons.filled.`Arrow-big-left`
import compose.icons.tablericons.filled.`Arrow-big-right-line`
import compose.icons.tablericons.filled.`Arrow-big-right-lines`
import compose.icons.tablericons.filled.`Arrow-big-right`
import compose.icons.tablericons.filled.`Arrow-big-up-line`
import compose.icons.tablericons.filled.`Arrow-big-up-lines`
import compose.icons.tablericons.filled.`Arrow-big-up`
import compose.icons.tablericons.filled.`Arrow-down-circle`
import compose.icons.tablericons.filled.`Arrow-down-rhombus`
import compose.icons.tablericons.filled.`Arrow-down-square`
import compose.icons.tablericons.filled.`Arrow-guide`
import compose.icons.tablericons.filled.`Arrow-left-circle`
import compose.icons.tablericons.filled.`Arrow-left-rhombus`
import compose.icons.tablericons.filled.`Arrow-left-square`
import compose.icons.tablericons.filled.`Arrow-move-down`
import compose.icons.tablericons.filled.`Arrow-move-left`
import compose.icons.tablericons.filled.`Arrow-move-right`
import compose.icons.tablericons.filled.`Arrow-move-up`
import compose.icons.tablericons.filled.`Arrow-right-circle`
import compose.icons.tablericons.filled.`Arrow-right-rhombus`
import compose.icons.tablericons.filled.`Arrow-right-square`
import compose.icons.tablericons.filled.`Arrow-up-circle`
import compose.icons.tablericons.filled.`Arrow-up-rhombus`
import compose.icons.tablericons.filled.`Arrow-up-square`
import compose.icons.tablericons.filled.`Aspect-ratio`
import compose.icons.tablericons.filled.`Atom-2`
import compose.icons.tablericons.filled.`Automatic-gearbox`
import compose.icons.tablericons.filled.`Baby-carriage`
import compose.icons.tablericons.filled.`Badge-3d`
import compose.icons.tablericons.filled.`Badge-4k`
import compose.icons.tablericons.filled.`Badge-8k`
import compose.icons.tablericons.filled.`Badge-ad`
import compose.icons.tablericons.filled.`Badge-ar`
import compose.icons.tablericons.filled.`Badge-cc`
import compose.icons.tablericons.filled.`Badge-hd`
import compose.icons.tablericons.filled.`Badge-sd`
import compose.icons.tablericons.filled.`Badge-tm`
import compose.icons.tablericons.filled.`Badge-vo`
import compose.icons.tablericons.filled.`Badge-vr`
import compose.icons.tablericons.filled.`Badge-wc`
import compose.icons.tablericons.filled.`Barrier-block`
import compose.icons.tablericons.filled.`Battery-1`
import compose.icons.tablericons.filled.`Battery-2`
import compose.icons.tablericons.filled.`Battery-3`
import compose.icons.tablericons.filled.`Battery-4`
import compose.icons.tablericons.filled.`Battery-automotive`
import compose.icons.tablericons.filled.`Battery-vertical-1`
import compose.icons.tablericons.filled.`Battery-vertical-2`
import compose.icons.tablericons.filled.`Battery-vertical-3`
import compose.icons.tablericons.filled.`Battery-vertical-4`
import compose.icons.tablericons.filled.`Battery-vertical`
import compose.icons.tablericons.filled.`Bed-flat`
import compose.icons.tablericons.filled.`Bell-minus`
import compose.icons.tablericons.filled.`Bell-plus`
import compose.icons.tablericons.filled.`Bell-ringing-2`
import compose.icons.tablericons.filled.`Bell-ringing`
import compose.icons.tablericons.filled.`Bell-x`
import compose.icons.tablericons.filled.`Bell-z`
import compose.icons.tablericons.filled.`Binary-tree-2`
import compose.icons.tablericons.filled.`Binary-tree`
import compose.icons.tablericons.filled.`Bounce-left`
import compose.icons.tablericons.filled.`Bounce-right`
import compose.icons.tablericons.filled.`Bowl-chopsticks`
import compose.icons.tablericons.filled.`Bowl-spoon`
import compose.icons.tablericons.filled.`Box-align-bottom-left`
import compose.icons.tablericons.filled.`Box-align-bottom-right`
import compose.icons.tablericons.filled.`Box-align-bottom`
import compose.icons.tablericons.filled.`Box-align-left`
import compose.icons.tablericons.filled.`Box-align-right`
import compose.icons.tablericons.filled.`Box-align-top-left`
import compose.icons.tablericons.filled.`Box-align-top-right`
import compose.icons.tablericons.filled.`Box-align-top`
import compose.icons.tablericons.filled.`Box-multiple`
import compose.icons.tablericons.filled.`Brand-angular`
import compose.icons.tablericons.filled.`Brand-apple`
import compose.icons.tablericons.filled.`Brand-bitbucket`
import compose.icons.tablericons.filled.`Brand-discord`
import compose.icons.tablericons.filled.`Brand-dribbble`
import compose.icons.tablericons.filled.`Brand-facebook`
import compose.icons.tablericons.filled.`Brand-github`
import compose.icons.tablericons.filled.`Brand-google`
import compose.icons.tablericons.filled.`Brand-instagram`
import compose.icons.tablericons.filled.`Brand-kick`
import compose.icons.tablericons.filled.`Brand-linkedin`
import compose.icons.tablericons.filled.`Brand-messenger`
import compose.icons.tablericons.filled.`Brand-open-source`
import compose.icons.tablericons.filled.`Brand-opera`
import compose.icons.tablericons.filled.`Brand-patreon`
import compose.icons.tablericons.filled.`Brand-paypal`
import compose.icons.tablericons.filled.`Brand-pinterest`
import compose.icons.tablericons.filled.`Brand-sketch`
import compose.icons.tablericons.filled.`Brand-snapchat`
import compose.icons.tablericons.filled.`Brand-spotify`
import compose.icons.tablericons.filled.`Brand-steam`
import compose.icons.tablericons.filled.`Brand-stripe`
import compose.icons.tablericons.filled.`Brand-tabler`
import compose.icons.tablericons.filled.`Brand-tiktok`
import compose.icons.tablericons.filled.`Brand-tinder`
import compose.icons.tablericons.filled.`Brand-tumblr`
import compose.icons.tablericons.filled.`Brand-twitter`
import compose.icons.tablericons.filled.`Brand-vercel`
import compose.icons.tablericons.filled.`Brand-vimeo`
import compose.icons.tablericons.filled.`Brand-weibo`
import compose.icons.tablericons.filled.`Brand-whatsapp`
import compose.icons.tablericons.filled.`Brand-windows`
import compose.icons.tablericons.filled.`Brand-x`
import compose.icons.tablericons.filled.`Brand-youtube`
import compose.icons.tablericons.filled.`Briefcase-2`
import compose.icons.tablericons.filled.`Brightness-auto`
import compose.icons.tablericons.filled.`Brightness-down`
import compose.icons.tablericons.filled.`Brightness-up`
import compose.icons.tablericons.filled.`Bubble-text`
import compose.icons.tablericons.filled.`Building-bridge-2`
import compose.icons.tablericons.filled.`Building-broadcast-tower`
import compose.icons.tablericons.filled.`Calendar-event`
import compose.icons.tablericons.filled.`Calendar-month`
import compose.icons.tablericons.filled.`Calendar-week`
import compose.icons.tablericons.filled.`Capsule-horizontal`
import compose.icons.tablericons.filled.`Car-4wd`
import compose.icons.tablericons.filled.`Car-crane`
import compose.icons.tablericons.filled.`Car-fan`
import compose.icons.tablericons.filled.`Car-suv`
import compose.icons.tablericons.filled.`Caret-down`
import compose.icons.tablericons.filled.`Caret-left-right`
import compose.icons.tablericons.filled.`Caret-left`
import compose.icons.tablericons.filled.`Caret-right`
import compose.icons.tablericons.filled.`Caret-up-down`
import compose.icons.tablericons.filled.`Caret-up`
import compose.icons.tablericons.filled.`Carousel-horizontal`
import compose.icons.tablericons.filled.`Carousel-vertical`
import compose.icons.tablericons.filled.`Cash-banknote`
import compose.icons.tablericons.filled.`Charging-pile`
import compose.icons.tablericons.filled.`Chart-area-line`
import compose.icons.tablericons.filled.`Chart-area`
import compose.icons.tablericons.filled.`Chart-bubble`
import compose.icons.tablericons.filled.`Chart-candle`
import compose.icons.tablericons.filled.`Chart-donut`
import compose.icons.tablericons.filled.`Chart-dots-2`
import compose.icons.tablericons.filled.`Chart-dots-3`
import compose.icons.tablericons.filled.`Chart-dots`
import compose.icons.tablericons.filled.`Chart-funnel`
import compose.icons.tablericons.filled.`Chart-grid-dots`
import compose.icons.tablericons.filled.`Chart-pie-2`
import compose.icons.tablericons.filled.`Chart-pie-3`
import compose.icons.tablericons.filled.`Chart-pie-4`
import compose.icons.tablericons.filled.`Chart-pie`
import compose.icons.tablericons.filled.`Chef-hat`
import compose.icons.tablericons.filled.`Chess-bishop`
import compose.icons.tablericons.filled.`Chess-king`
import compose.icons.tablericons.filled.`Chess-knight`
import compose.icons.tablericons.filled.`Chess-queen`
import compose.icons.tablericons.filled.`Chess-rook`
import compose.icons.tablericons.filled.`Christmas-tree`
import compose.icons.tablericons.filled.`Circle-arrow-down-left`
import compose.icons.tablericons.filled.`Circle-arrow-down-right`
import compose.icons.tablericons.filled.`Circle-arrow-down`
import compose.icons.tablericons.filled.`Circle-arrow-left`
import compose.icons.tablericons.filled.`Circle-arrow-right`
import compose.icons.tablericons.filled.`Circle-arrow-up-left`
import compose.icons.tablericons.filled.`Circle-arrow-up-right`
import compose.icons.tablericons.filled.`Circle-arrow-up`
import compose.icons.tablericons.filled.`Circle-caret-down`
import compose.icons.tablericons.filled.`Circle-caret-left`
import compose.icons.tablericons.filled.`Circle-caret-right`
import compose.icons.tablericons.filled.`Circle-caret-up`
import compose.icons.tablericons.filled.`Circle-check`
import compose.icons.tablericons.filled.`Circle-chevron-down`
import compose.icons.tablericons.filled.`Circle-chevron-left`
import compose.icons.tablericons.filled.`Circle-chevron-right`
import compose.icons.tablericons.filled.`Circle-chevron-up`
import compose.icons.tablericons.filled.`Circle-chevrons-down`
import compose.icons.tablericons.filled.`Circle-chevrons-left`
import compose.icons.tablericons.filled.`Circle-chevrons-right`
import compose.icons.tablericons.filled.`Circle-chevrons-up`
import compose.icons.tablericons.filled.`Circle-dot`
import compose.icons.tablericons.filled.`Circle-key`
import compose.icons.tablericons.filled.`Circle-letter-a`
import compose.icons.tablericons.filled.`Circle-letter-b`
import compose.icons.tablericons.filled.`Circle-letter-c`
import compose.icons.tablericons.filled.`Circle-letter-d`
import compose.icons.tablericons.filled.`Circle-letter-e`
import compose.icons.tablericons.filled.`Circle-letter-f`
import compose.icons.tablericons.filled.`Circle-letter-g`
import compose.icons.tablericons.filled.`Circle-letter-h`
import compose.icons.tablericons.filled.`Circle-letter-i`
import compose.icons.tablericons.filled.`Circle-letter-j`
import compose.icons.tablericons.filled.`Circle-letter-k`
import compose.icons.tablericons.filled.`Circle-letter-l`
import compose.icons.tablericons.filled.`Circle-letter-m`
import compose.icons.tablericons.filled.`Circle-letter-n`
import compose.icons.tablericons.filled.`Circle-letter-o`
import compose.icons.tablericons.filled.`Circle-letter-p`
import compose.icons.tablericons.filled.`Circle-letter-q`
import compose.icons.tablericons.filled.`Circle-letter-r`
import compose.icons.tablericons.filled.`Circle-letter-s`
import compose.icons.tablericons.filled.`Circle-letter-t`
import compose.icons.tablericons.filled.`Circle-letter-u`
import compose.icons.tablericons.filled.`Circle-letter-v`
import compose.icons.tablericons.filled.`Circle-letter-w`
import compose.icons.tablericons.filled.`Circle-letter-x`
import compose.icons.tablericons.filled.`Circle-letter-y`
import compose.icons.tablericons.filled.`Circle-letter-z`
import compose.icons.tablericons.filled.`Circle-number-0`
import compose.icons.tablericons.filled.`Circle-number-1`
import compose.icons.tablericons.filled.`Circle-number-2`
import compose.icons.tablericons.filled.`Circle-number-3`
import compose.icons.tablericons.filled.`Circle-number-4`
import compose.icons.tablericons.filled.`Circle-number-5`
import compose.icons.tablericons.filled.`Circle-number-6`
import compose.icons.tablericons.filled.`Circle-number-7`
import compose.icons.tablericons.filled.`Circle-number-8`
import compose.icons.tablericons.filled.`Circle-number-9`
import compose.icons.tablericons.filled.`Circle-percentage`
import compose.icons.tablericons.filled.`Circle-plus`
import compose.icons.tablericons.filled.`Circle-rectangle`
import compose.icons.tablericons.filled.`Circle-x`
import compose.icons.tablericons.filled.`Clipboard-check`
import compose.icons.tablericons.filled.`Clipboard-data`
import compose.icons.tablericons.filled.`Clipboard-list`
import compose.icons.tablericons.filled.`Clipboard-plus`
import compose.icons.tablericons.filled.`Clipboard-smile`
import compose.icons.tablericons.filled.`Clipboard-text`
import compose.icons.tablericons.filled.`Clipboard-typography`
import compose.icons.tablericons.filled.`Clipboard-x`
import compose.icons.tablericons.filled.`Clock-hour-10`
import compose.icons.tablericons.filled.`Clock-hour-11`
import compose.icons.tablericons.filled.`Clock-hour-12`
import compose.icons.tablericons.filled.`Clock-hour-1`
import compose.icons.tablericons.filled.`Clock-hour-2`
import compose.icons.tablericons.filled.`Clock-hour-3`
import compose.icons.tablericons.filled.`Clock-hour-4`
import compose.icons.tablericons.filled.`Clock-hour-5`
import compose.icons.tablericons.filled.`Clock-hour-6`
import compose.icons.tablericons.filled.`Clock-hour-7`
import compose.icons.tablericons.filled.`Clock-hour-8`
import compose.icons.tablericons.filled.`Clock-hour-9`
import compose.icons.tablericons.filled.`Cloud-computing`
import compose.icons.tablericons.filled.`Cloud-data-connection`
import compose.icons.tablericons.filled.`Code-circle-2`
import compose.icons.tablericons.filled.`Code-circle`
import compose.icons.tablericons.filled.`Coin-bitcoin`
import compose.icons.tablericons.filled.`Coin-euro`
import compose.icons.tablericons.filled.`Coin-monero`
import compose.icons.tablericons.filled.`Coin-pound`
import compose.icons.tablericons.filled.`Coin-rupee`
import compose.icons.tablericons.filled.`Coin-taka`
import compose.icons.tablericons.filled.`Coin-yen`
import compose.icons.tablericons.filled.`Coin-yuan`
import compose.icons.tablericons.filled.`Columns-1`
import compose.icons.tablericons.filled.`Columns-2`
import compose.icons.tablericons.filled.`Columns-3`
import compose.icons.tablericons.filled.`Cone-2`
import compose.icons.tablericons.filled.`Contrast-2`
import compose.icons.tablericons.filled.`Cookie-man`
import compose.icons.tablericons.filled.`Copy-check`
import compose.icons.tablericons.filled.`Copy-minus`
import compose.icons.tablericons.filled.`Copy-plus`
import compose.icons.tablericons.filled.`Copy-x`
import compose.icons.tablericons.filled.`Credit-card`
import compose.icons.tablericons.filled.`Crop-1-1`
import compose.icons.tablericons.filled.`Crop-16-9`
import compose.icons.tablericons.filled.`Crop-3-2`
import compose.icons.tablericons.filled.`Crop-5-4`
import compose.icons.tablericons.filled.`Crop-7-5`
import compose.icons.tablericons.filled.`Crop-landscape`
import compose.icons.tablericons.filled.`Crop-portrait`
import compose.icons.tablericons.filled.`Current-location`
import compose.icons.tablericons.filled.`Device-cctv`
import compose.icons.tablericons.filled.`Device-desktop`
import compose.icons.tablericons.filled.`Device-gamepad-3`
import compose.icons.tablericons.filled.`Device-gamepad`
import compose.icons.tablericons.filled.`Device-heart-monitor`
import compose.icons.tablericons.filled.`Device-imac`
import compose.icons.tablericons.filled.`Device-ipad`
import compose.icons.tablericons.filled.`Device-mobile`
import compose.icons.tablericons.filled.`Device-remote`
import compose.icons.tablericons.filled.`Device-speaker`
import compose.icons.tablericons.filled.`Device-tablet`
import compose.icons.tablericons.filled.`Device-tv-old`
import compose.icons.tablericons.filled.`Device-tv`
import compose.icons.tablericons.filled.`Device-unknown`
import compose.icons.tablericons.filled.`Device-usb`
import compose.icons.tablericons.filled.`Device-vision-pro`
import compose.icons.tablericons.filled.`Device-watch`
import compose.icons.tablericons.filled.`Dice-1`
import compose.icons.tablericons.filled.`Dice-2`
import compose.icons.tablericons.filled.`Dice-3`
import compose.icons.tablericons.filled.`Dice-4`
import compose.icons.tablericons.filled.`Dice-5`
import compose.icons.tablericons.filled.`Dice-6`
import compose.icons.tablericons.filled.`Direction-arrows`
import compose.icons.tablericons.filled.`Direction-sign`
import compose.icons.tablericons.filled.`Drop-circle`
import compose.icons.tablericons.filled.`Droplet-half-2`
import compose.icons.tablericons.filled.`Droplet-half`
import compose.icons.tablericons.filled.`Dual-screen`
import compose.icons.tablericons.filled.`Ease-in-control-point`
import compose.icons.tablericons.filled.`Ease-in-out-control-points`
import compose.icons.tablericons.filled.`Ease-out-control-point`
import compose.icons.tablericons.filled.`Egg-cracked`
import compose.icons.tablericons.filled.`Egg-fried`
import compose.icons.tablericons.filled.`Escalator-down`
import compose.icons.tablericons.filled.`Escalator-up`
import compose.icons.tablericons.filled.`Exclamation-circle`
import compose.icons.tablericons.filled.`Eye-table`
import compose.icons.tablericons.filled.`Eyeglass-2`
import compose.icons.tablericons.filled.`Face-mask`
import compose.icons.tablericons.filled.`Fidget-spinner`
import compose.icons.tablericons.filled.`File-analytics`
import compose.icons.tablericons.filled.`File-check`
import compose.icons.tablericons.filled.`File-code-2`
import compose.icons.tablericons.filled.`File-code`
import compose.icons.tablericons.filled.`File-cv`
import compose.icons.tablericons.filled.`File-delta`
import compose.icons.tablericons.filled.`File-description`
import compose.icons.tablericons.filled.`File-diff`
import compose.icons.tablericons.filled.`File-digit`
import compose.icons.tablericons.filled.`File-dollar`
import compose.icons.tablericons.filled.`File-dots`
import compose.icons.tablericons.filled.`File-download`
import compose.icons.tablericons.filled.`File-euro`
import compose.icons.tablericons.filled.`File-function`
import compose.icons.tablericons.filled.`File-horizontal`
import compose.icons.tablericons.filled.`File-info`
import compose.icons.tablericons.filled.`File-invoice`
import compose.icons.tablericons.filled.`File-lambda`
import compose.icons.tablericons.filled.`File-minus`
import compose.icons.tablericons.filled.`File-music`
import compose.icons.tablericons.filled.`File-neutral`
import compose.icons.tablericons.filled.`File-pencil`
import compose.icons.tablericons.filled.`File-percent`
import compose.icons.tablericons.filled.`File-phone`
import compose.icons.tablericons.filled.`File-power`
import compose.icons.tablericons.filled.`File-rss`
import compose.icons.tablericons.filled.`File-sad`
import compose.icons.tablericons.filled.`File-scissors`
import compose.icons.tablericons.filled.`File-settings`
import compose.icons.tablericons.filled.`File-signal`
import compose.icons.tablericons.filled.`File-smile`
import compose.icons.tablericons.filled.`File-star`
import compose.icons.tablericons.filled.`File-text`
import compose.icons.tablericons.filled.`File-time`
import compose.icons.tablericons.filled.`File-typography`
import compose.icons.tablericons.filled.`File-unknown`
import compose.icons.tablericons.filled.`File-upload`
import compose.icons.tablericons.filled.`File-vector`
import compose.icons.tablericons.filled.`File-x`
import compose.icons.tablericons.filled.`Fish-bone`
import compose.icons.tablericons.filled.`Flag-2`
import compose.icons.tablericons.filled.`Flag-3`
import compose.icons.tablericons.filled.`Flask-2`
import compose.icons.tablericons.filled.`Folder-open`
import compose.icons.tablericons.filled.`Forbid-2`
import compose.icons.tablericons.filled.`Garden-cart`
import compose.icons.tablericons.filled.`Gas-station`
import compose.icons.tablericons.filled.`Ghost-2`
import compose.icons.tablericons.filled.`Ghost-3`
import compose.icons.tablericons.filled.`Gift-card`
import compose.icons.tablericons.filled.`Glass-full`
import compose.icons.tablericons.filled.`Grid-pattern`
import compose.icons.tablericons.filled.`Guitar-pick`
import compose.icons.tablericons.filled.`Hanger-2`
import compose.icons.tablericons.filled.`Heart-broken`
import compose.icons.tablericons.filled.`Helicopter-landing`
import compose.icons.tablericons.filled.`Help-circle`
import compose.icons.tablericons.filled.`Help-hexagon`
import compose.icons.tablericons.filled.`Help-octagon`
import compose.icons.tablericons.filled.`Help-square-rounded`
import compose.icons.tablericons.filled.`Help-square`
import compose.icons.tablericons.filled.`Help-triangle`
import compose.icons.tablericons.filled.`Hexagon-letter-a`
import compose.icons.tablericons.filled.`Hexagon-letter-b`
import compose.icons.tablericons.filled.`Hexagon-letter-c`
import compose.icons.tablericons.filled.`Hexagon-letter-d`
import compose.icons.tablericons.filled.`Hexagon-letter-e`
import compose.icons.tablericons.filled.`Hexagon-letter-f`
import compose.icons.tablericons.filled.`Hexagon-letter-g`
import compose.icons.tablericons.filled.`Hexagon-letter-h`
import compose.icons.tablericons.filled.`Hexagon-letter-i`
import compose.icons.tablericons.filled.`Hexagon-letter-j`
import compose.icons.tablericons.filled.`Hexagon-letter-k`
import compose.icons.tablericons.filled.`Hexagon-letter-l`
import compose.icons.tablericons.filled.`Hexagon-letter-m`
import compose.icons.tablericons.filled.`Hexagon-letter-n`
import compose.icons.tablericons.filled.`Hexagon-letter-o`
import compose.icons.tablericons.filled.`Hexagon-letter-p`
import compose.icons.tablericons.filled.`Hexagon-letter-q`
import compose.icons.tablericons.filled.`Hexagon-letter-r`
import compose.icons.tablericons.filled.`Hexagon-letter-s`
import compose.icons.tablericons.filled.`Hexagon-letter-t`
import compose.icons.tablericons.filled.`Hexagon-letter-u`
import compose.icons.tablericons.filled.`Hexagon-letter-v`
import compose.icons.tablericons.filled.`Hexagon-letter-w`
import compose.icons.tablericons.filled.`Hexagon-letter-x`
import compose.icons.tablericons.filled.`Hexagon-letter-y`
import compose.icons.tablericons.filled.`Hexagon-letter-z`
import compose.icons.tablericons.filled.`Hexagon-minus`
import compose.icons.tablericons.filled.`Hexagon-number-0`
import compose.icons.tablericons.filled.`Hexagon-number-1`
import compose.icons.tablericons.filled.`Hexagon-number-2`
import compose.icons.tablericons.filled.`Hexagon-number-3`
import compose.icons.tablericons.filled.`Hexagon-number-4`
import compose.icons.tablericons.filled.`Hexagon-number-5`
import compose.icons.tablericons.filled.`Hexagon-number-6`
import compose.icons.tablericons.filled.`Hexagon-number-7`
import compose.icons.tablericons.filled.`Hexagon-number-8`
import compose.icons.tablericons.filled.`Hexagon-number-9`
import compose.icons.tablericons.filled.`Hexagon-plus`
import compose.icons.tablericons.filled.`Hospital-circle`
import compose.icons.tablericons.filled.`Info-circle`
import compose.icons.tablericons.filled.`Info-hexagon`
import compose.icons.tablericons.filled.`Info-octagon`
import compose.icons.tablericons.filled.`Info-square-rounded`
import compose.icons.tablericons.filled.`Info-square`
import compose.icons.tablericons.filled.`Info-triangle`
import compose.icons.tablericons.filled.`Inner-shadow-bottom-left`
import compose.icons.tablericons.filled.`Inner-shadow-bottom-right`
import compose.icons.tablericons.filled.`Inner-shadow-bottom`
import compose.icons.tablericons.filled.`Inner-shadow-left`
import compose.icons.tablericons.filled.`Inner-shadow-right`
import compose.icons.tablericons.filled.`Inner-shadow-top-left`
import compose.icons.tablericons.filled.`Inner-shadow-top-right`
import compose.icons.tablericons.filled.`Inner-shadow-top`
import compose.icons.tablericons.filled.`Ironing-1`
import compose.icons.tablericons.filled.`Ironing-2`
import compose.icons.tablericons.filled.`Ironing-3`
import compose.icons.tablericons.filled.`Ironing-steam`
import compose.icons.tablericons.filled.`Jewish-star`
import compose.icons.tablericons.filled.`Keyframe-align-center`
import compose.icons.tablericons.filled.`Keyframe-align-horizontal`
import compose.icons.tablericons.filled.`Keyframe-align-vertical`
import compose.icons.tablericons.filled.`Label-important`
import compose.icons.tablericons.filled.`Lasso-polygon`
import compose.icons.tablericons.filled.`Laurel-wreath-1`
import compose.icons.tablericons.filled.`Laurel-wreath-2`
import compose.icons.tablericons.filled.`Laurel-wreath-3`
import compose.icons.tablericons.filled.`Laurel-wreath`
import compose.icons.tablericons.filled.`Layout-2`
import compose.icons.tablericons.filled.`Layout-align-bottom`
import compose.icons.tablericons.filled.`Layout-align-center`
import compose.icons.tablericons.filled.`Layout-align-left`
import compose.icons.tablericons.filled.`Layout-align-middle`
import compose.icons.tablericons.filled.`Layout-align-right`
import compose.icons.tablericons.filled.`Layout-align-top`
import compose.icons.tablericons.filled.`Layout-board-split`
import compose.icons.tablericons.filled.`Layout-board`
import compose.icons.tablericons.filled.`Layout-bottombar-collapse`
import compose.icons.tablericons.filled.`Layout-bottombar-expand`
import compose.icons.tablericons.filled.`Layout-bottombar`
import compose.icons.tablericons.filled.`Layout-cards`
import compose.icons.tablericons.filled.`Layout-dashboard`
import compose.icons.tablericons.filled.`Layout-distribute-horizontal`
import compose.icons.tablericons.filled.`Layout-distribute-vertical`
import compose.icons.tablericons.filled.`Layout-grid`
import compose.icons.tablericons.filled.`Layout-kanban`
import compose.icons.tablericons.filled.`Layout-list`
import compose.icons.tablericons.filled.`Layout-navbar-collapse`
import compose.icons.tablericons.filled.`Layout-navbar-expand`
import compose.icons.tablericons.filled.`Layout-navbar`
import compose.icons.tablericons.filled.`Layout-sidebar-left-collapse`
import compose.icons.tablericons.filled.`Layout-sidebar-left-expand`
import compose.icons.tablericons.filled.`Layout-sidebar-right-collapse`
import compose.icons.tablericons.filled.`Layout-sidebar-right-expand`
import compose.icons.tablericons.filled.`Layout-sidebar-right`
import compose.icons.tablericons.filled.`Layout-sidebar`
import compose.icons.tablericons.filled.`Lemon-2`
import compose.icons.tablericons.filled.`Library-plus`
import compose.icons.tablericons.filled.`Live-photo`
import compose.icons.tablericons.filled.`Live-view`
import compose.icons.tablericons.filled.`Lock-square-rounded`
import compose.icons.tablericons.filled.`Mail-opened`
import compose.icons.tablericons.filled.`Manual-gearbox`
import compose.icons.tablericons.filled.`Map-pin`
import compose.icons.tablericons.filled.`Medical-cross`
import compose.icons.tablericons.filled.`Message-2`
import compose.icons.tablericons.filled.`Message-chatbot`
import compose.icons.tablericons.filled.`Message-circle`
import compose.icons.tablericons.filled.`Message-report`
import compose.icons.tablericons.filled.`Michelin-star`
import compose.icons.tablericons.filled.`Military-rank`
import compose.icons.tablericons.filled.`Mood-angry`
import compose.icons.tablericons.filled.`Mood-confuzed`
import compose.icons.tablericons.filled.`Mood-crazy-happy`
import compose.icons.tablericons.filled.`Mood-empty`
import compose.icons.tablericons.filled.`Mood-happy`
import compose.icons.tablericons.filled.`Mood-kid`
import compose.icons.tablericons.filled.`Mood-neutral`
import compose.icons.tablericons.filled.`Mood-sad`
import compose.icons.tablericons.filled.`Mood-smile`
import compose.icons.tablericons.filled.`Mood-wrrr`
import compose.icons.tablericons.filled.`Octagon-minus`
import compose.icons.tablericons.filled.`Octagon-plus`
import compose.icons.tablericons.filled.`Oval-vertical`
import compose.icons.tablericons.filled.`Panorama-horizontal`
import compose.icons.tablericons.filled.`Panorama-vertical`
import compose.icons.tablericons.filled.`Parking-circle`
import compose.icons.tablericons.filled.`Pennant-2`
import compose.icons.tablericons.filled.`Picture-in-picture-top`
import compose.icons.tablericons.filled.`Picture-in-picture`
import compose.icons.tablericons.filled.`Play-card-10`
import compose.icons.tablericons.filled.`Play-card-1`
import compose.icons.tablericons.filled.`Play-card-2`
import compose.icons.tablericons.filled.`Play-card-3`
import compose.icons.tablericons.filled.`Play-card-4`
import compose.icons.tablericons.filled.`Play-card-5`
import compose.icons.tablericons.filled.`Play-card-6`
import compose.icons.tablericons.filled.`Play-card-7`
import compose.icons.tablericons.filled.`Play-card-8`
import compose.icons.tablericons.filled.`Play-card-9`
import compose.icons.tablericons.filled.`Play-card-a`
import compose.icons.tablericons.filled.`Play-card-j`
import compose.icons.tablericons.filled.`Play-card-k`
import compose.icons.tablericons.filled.`Play-card-q`
import compose.icons.tablericons.filled.`Play-card-star`
import compose.icons.tablericons.filled.`Player-eject`
import compose.icons.tablericons.filled.`Player-pause`
import compose.icons.tablericons.filled.`Player-play`
import compose.icons.tablericons.filled.`Player-record`
import compose.icons.tablericons.filled.`Player-skip-back`
import compose.icons.tablericons.filled.`Player-skip-forward`
import compose.icons.tablericons.filled.`Player-stop`
import compose.icons.tablericons.filled.`Player-track-next`
import compose.icons.tablericons.filled.`Player-track-prev`
import compose.icons.tablericons.filled.`Presentation-analytics`
import compose.icons.tablericons.filled.`Receipt-dollar`
import compose.icons.tablericons.filled.`Receipt-euro`
import compose.icons.tablericons.filled.`Receipt-pound`
import compose.icons.tablericons.filled.`Receipt-rupee`
import compose.icons.tablericons.filled.`Receipt-yen`
import compose.icons.tablericons.filled.`Receipt-yuan`
import compose.icons.tablericons.filled.`Rectangle-vertical`
import compose.icons.tablericons.filled.`Relation-many-to-many`
import compose.icons.tablericons.filled.`Relation-one-to-many`
import compose.icons.tablericons.filled.`Relation-one-to-one`
import compose.icons.tablericons.filled.`Rosette-discount-check`
import compose.icons.tablericons.filled.`Rosette-discount`
import compose.icons.tablericons.filled.`Scuba-diving-tank`
import compose.icons.tablericons.filled.`Shield-check`
import compose.icons.tablericons.filled.`Shield-checkered`
import compose.icons.tablericons.filled.`Shield-half`
import compose.icons.tablericons.filled.`Shield-lock`
import compose.icons.tablericons.filled.`Shopping-cart`
import compose.icons.tablericons.filled.`Sign-left`
import compose.icons.tablericons.filled.`Sign-right`
import compose.icons.tablericons.filled.`Sort-ascending-2`
import compose.icons.tablericons.filled.`Sort-ascending-shapes`
import compose.icons.tablericons.filled.`Sort-descending-2`
import compose.icons.tablericons.filled.`Sort-descending-shapes`
import compose.icons.tablericons.filled.`Square-arrow-down`
import compose.icons.tablericons.filled.`Square-arrow-left`
import compose.icons.tablericons.filled.`Square-arrow-right`
import compose.icons.tablericons.filled.`Square-arrow-up`
import compose.icons.tablericons.filled.`Square-asterisk`
import compose.icons.tablericons.filled.`Square-check`
import compose.icons.tablericons.filled.`Square-chevron-down`
import compose.icons.tablericons.filled.`Square-chevron-left`
import compose.icons.tablericons.filled.`Square-chevron-right`
import compose.icons.tablericons.filled.`Square-chevron-up`
import compose.icons.tablericons.filled.`Square-chevrons-down`
import compose.icons.tablericons.filled.`Square-chevrons-left`
import compose.icons.tablericons.filled.`Square-chevrons-right`
import compose.icons.tablericons.filled.`Square-chevrons-up`
import compose.icons.tablericons.filled.`Square-dot`
import compose.icons.tablericons.filled.`Square-f0`
import compose.icons.tablericons.filled.`Square-f1`
import compose.icons.tablericons.filled.`Square-f2`
import compose.icons.tablericons.filled.`Square-f3`
import compose.icons.tablericons.filled.`Square-f4`
import compose.icons.tablericons.filled.`Square-f5`
import compose.icons.tablericons.filled.`Square-f6`
import compose.icons.tablericons.filled.`Square-f7`
import compose.icons.tablericons.filled.`Square-f8`
import compose.icons.tablericons.filled.`Square-f9`
import compose.icons.tablericons.filled.`Square-letter-a`
import compose.icons.tablericons.filled.`Square-letter-b`
import compose.icons.tablericons.filled.`Square-letter-c`
import compose.icons.tablericons.filled.`Square-letter-d`
import compose.icons.tablericons.filled.`Square-letter-e`
import compose.icons.tablericons.filled.`Square-letter-f`
import compose.icons.tablericons.filled.`Square-letter-g`
import compose.icons.tablericons.filled.`Square-letter-h`
import compose.icons.tablericons.filled.`Square-letter-i`
import compose.icons.tablericons.filled.`Square-letter-j`
import compose.icons.tablericons.filled.`Square-letter-k`
import compose.icons.tablericons.filled.`Square-letter-l`
import compose.icons.tablericons.filled.`Square-letter-m`
import compose.icons.tablericons.filled.`Square-letter-n`
import compose.icons.tablericons.filled.`Square-letter-o`
import compose.icons.tablericons.filled.`Square-letter-p`
import compose.icons.tablericons.filled.`Square-letter-q`
import compose.icons.tablericons.filled.`Square-letter-r`
import compose.icons.tablericons.filled.`Square-letter-s`
import compose.icons.tablericons.filled.`Square-letter-t`
import compose.icons.tablericons.filled.`Square-letter-u`
import compose.icons.tablericons.filled.`Square-letter-v`
import compose.icons.tablericons.filled.`Square-letter-w`
import compose.icons.tablericons.filled.`Square-letter-x`
import compose.icons.tablericons.filled.`Square-letter-y`
import compose.icons.tablericons.filled.`Square-letter-z`
import compose.icons.tablericons.filled.`Square-minus`
import compose.icons.tablericons.filled.`Square-number-0`
import compose.icons.tablericons.filled.`Square-number-1`
import compose.icons.tablericons.filled.`Square-number-2`
import compose.icons.tablericons.filled.`Square-number-3`
import compose.icons.tablericons.filled.`Square-number-4`
import compose.icons.tablericons.filled.`Square-number-5`
import compose.icons.tablericons.filled.`Square-number-6`
import compose.icons.tablericons.filled.`Square-number-7`
import compose.icons.tablericons.filled.`Square-number-8`
import compose.icons.tablericons.filled.`Square-number-9`
import compose.icons.tablericons.filled.`Square-rotated`
import compose.icons.tablericons.filled.`Square-rounded-arrow-down`
import compose.icons.tablericons.filled.`Square-rounded-arrow-left`
import compose.icons.tablericons.filled.`Square-rounded-arrow-right`
import compose.icons.tablericons.filled.`Square-rounded-arrow-up`
import compose.icons.tablericons.filled.`Square-rounded-check`
import compose.icons.tablericons.filled.`Square-rounded-chevron-down`
import compose.icons.tablericons.filled.`Square-rounded-chevron-left`
import compose.icons.tablericons.filled.`Square-rounded-chevron-right`
import compose.icons.tablericons.filled.`Square-rounded-chevron-up`
import compose.icons.tablericons.filled.`Square-rounded-chevrons-down`
import compose.icons.tablericons.filled.`Square-rounded-chevrons-left`
import compose.icons.tablericons.filled.`Square-rounded-chevrons-right`
import compose.icons.tablericons.filled.`Square-rounded-chevrons-up`
import compose.icons.tablericons.filled.`Square-rounded-letter-a`
import compose.icons.tablericons.filled.`Square-rounded-letter-b`
import compose.icons.tablericons.filled.`Square-rounded-letter-c`
import compose.icons.tablericons.filled.`Square-rounded-letter-d`
import compose.icons.tablericons.filled.`Square-rounded-letter-e`
import compose.icons.tablericons.filled.`Square-rounded-letter-f`
import compose.icons.tablericons.filled.`Square-rounded-letter-g`
import compose.icons.tablericons.filled.`Square-rounded-letter-h`
import compose.icons.tablericons.filled.`Square-rounded-letter-i`
import compose.icons.tablericons.filled.`Square-rounded-letter-j`
import compose.icons.tablericons.filled.`Square-rounded-letter-k`
import compose.icons.tablericons.filled.`Square-rounded-letter-l`
import compose.icons.tablericons.filled.`Square-rounded-letter-m`
import compose.icons.tablericons.filled.`Square-rounded-letter-n`
import compose.icons.tablericons.filled.`Square-rounded-letter-o`
import compose.icons.tablericons.filled.`Square-rounded-letter-p`
import compose.icons.tablericons.filled.`Square-rounded-letter-q`
import compose.icons.tablericons.filled.`Square-rounded-letter-r`
import compose.icons.tablericons.filled.`Square-rounded-letter-s`
import compose.icons.tablericons.filled.`Square-rounded-letter-t`
import compose.icons.tablericons.filled.`Square-rounded-letter-u`
import compose.icons.tablericons.filled.`Square-rounded-letter-v`
import compose.icons.tablericons.filled.`Square-rounded-letter-w`
import compose.icons.tablericons.filled.`Square-rounded-letter-x`
import compose.icons.tablericons.filled.`Square-rounded-letter-y`
import compose.icons.tablericons.filled.`Square-rounded-letter-z`
import compose.icons.tablericons.filled.`Square-rounded-minus`
import compose.icons.tablericons.filled.`Square-rounded-number-0`
import compose.icons.tablericons.filled.`Square-rounded-number-1`
import compose.icons.tablericons.filled.`Square-rounded-number-2`
import compose.icons.tablericons.filled.`Square-rounded-number-3`
import compose.icons.tablericons.filled.`Square-rounded-number-4`
import compose.icons.tablericons.filled.`Square-rounded-number-5`
import compose.icons.tablericons.filled.`Square-rounded-number-6`
import compose.icons.tablericons.filled.`Square-rounded-number-7`
import compose.icons.tablericons.filled.`Square-rounded-number-8`
import compose.icons.tablericons.filled.`Square-rounded-number-9`
import compose.icons.tablericons.filled.`Square-rounded-plus`
import compose.icons.tablericons.filled.`Square-rounded-x`
import compose.icons.tablericons.filled.`Square-rounded`
import compose.icons.tablericons.filled.`Square-x`
import compose.icons.tablericons.filled.`Stack-2`
import compose.icons.tablericons.filled.`Stack-3`
import compose.icons.tablericons.filled.`Star-half`
import compose.icons.tablericons.filled.`Steering-wheel`
import compose.icons.tablericons.filled.`Sun-high`
import compose.icons.tablericons.filled.`Sun-low`
import compose.icons.tablericons.filled.`Sunset-2`
import compose.icons.tablericons.filled.`Swipe-down`
import compose.icons.tablericons.filled.`Swipe-left`
import compose.icons.tablericons.filled.`Swipe-right`
import compose.icons.tablericons.filled.`Swipe-up`
import compose.icons.tablericons.filled.`Temperature-minus`
import compose.icons.tablericons.filled.`Temperature-plus`
import compose.icons.tablericons.filled.`Test-pipe-2`
import compose.icons.tablericons.filled.`Thumb-down`
import compose.icons.tablericons.filled.`Thumb-up`
import compose.icons.tablericons.filled.`Tilt-shift`
import compose.icons.tablericons.filled.`Timeline-event`
import compose.icons.tablericons.filled.`Toggle-left`
import compose.icons.tablericons.filled.`Toggle-right`
import compose.icons.tablericons.filled.`Transition-bottom`
import compose.icons.tablericons.filled.`Transition-left`
import compose.icons.tablericons.filled.`Transition-right`
import compose.icons.tablericons.filled.`Transition-top`
import compose.icons.tablericons.filled.`Trash-x`
import compose.icons.tablericons.filled.`Triangle-inverted`
import compose.icons.tablericons.filled.`Triangle-square-circle`
import compose.icons.tablericons.filled.`Video-minus`
import compose.icons.tablericons.filled.`Video-plus`
import compose.icons.tablericons.filled.`Writing-sign`
import compose.icons.tablericons.filled.`Xbox-a`
import compose.icons.tablericons.filled.`Xbox-b`
import compose.icons.tablericons.filled.`Xbox-x`
import compose.icons.tablericons.filled.`Xbox-y`
import compose.icons.tablericons.filled.`Yin-yang`
import compose.icons.tablericons.filled.`Zoom-cancel`
import compose.icons.tablericons.filled.`Zoom-check`
import compose.icons.tablericons.filled.`Zoom-code`
import compose.icons.tablericons.filled.`Zoom-exclamation`
import compose.icons.tablericons.filled.`Zoom-in-area`
import compose.icons.tablericons.filled.`Zoom-in`
import compose.icons.tablericons.filled.`Zoom-money`
import compose.icons.tablericons.filled.`Zoom-out-area`
import compose.icons.tablericons.filled.`Zoom-out`
import compose.icons.tablericons.filled.`Zoom-pan`
import compose.icons.tablericons.filled.`Zoom-question`
import compose.icons.tablericons.filled.`Zoom-scan`
import kotlin.String
import kotlin.collections.List as ____KtList
import kotlin.collections.Map as ____KtMap

public object FilledGroup

public val TablerIcons.Filled: FilledGroup
  get() = FilledGroup

public val FilledGroup.groupName: String
  get() = "filled"


